services:
  db:
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    volumes: !override []

  api:
    build:
      target: development
    ports: !override
      - "${HOST_BIND_IP}:${TEST_PORT}:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
