services:
  db:
    environment:
      - POSTGRES_DB=${POSTGRES_DEV_DB}
    volumes: !override []

  fapi-db-tmpl:
    build:
      target: development
    ports: !override
      - "${FAPI_TEMPL_HOST_BIND_IP}:${FAPI_TEMPL_DEV_PORT}:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DEV_DB}
    volumes:
      - .:/app
      - /app/.venv
