name: Setup Test
description: Setup Python environment for testing

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version

    - name: Install uv
      run: pipx install uv
      shell: bash

    - name: Install dependencies
      run: uv sync --frozen
      shell: bash

    - name: Create .env file for CI
      run: cp .env.example .env
      shell: bash