name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-root

      - name: Create .env.test file
        run: |
          echo "HOST_BIND_IP=${{ secrets.HOST_BIND_IP || '127.0.0.1' }}" >> .env.test
          echo "HOST_PORT=${{ secrets.HOST_PORT || '50001' }}" >> .env.test
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_TEST || 'postgresql+psycopg://user:password@localhost:5432/test-db' }}" >> .env.test
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER || 'user' }}" >> .env.test
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD || 'password' }}" >> .env.test
          echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME_TEST || 'test-db' }}" >> .env.test

      - name: Run tests
        run: make test SUDO=true
